import type { Metadata } from "next";
import { site } from "@/content/site";

export const metadata: Metadata = {
  title: "About ClearClients | Fintech, Cloud & AI Software Engineering",
  description: "Learn about ClearClients, a software engineering company focused on fintech systems, payment APIs, cloud engineering, DevOps and AI-enabled applications.",
  alternates: { canonical: "/about" }
};

export default function AboutPage() {
  return <main><section className="page-hero"><div className="container"><div className="eyebrow">ABOUT CLEARCLIENTS</div><h1>Software Engineering for Financial and Cloud Systems</h1><p>ClearClients builds fintech applications, payment infrastructure, backend systems, cloud-native software and AI-enabled applications.</p></div></section><section className="section"><div className="container"><div className="feature-grid"><div><h2>ClearClients</h2><p>ClearClients is a software engineering company focused on fintech systems, payment infrastructure, backend APIs, cloud applications, DevOps and artificial intelligence.</p><p>We design software around clear requirements, maintainable architecture, automated testing, reliable deployment and operational visibility.</p></div><div className="card"><h3>Engineering Principles</h3><p><strong>Build for Production</strong><br/>Validation, error handling, security controls and automated testing.</p><p><strong>Automate Delivery</strong><br/>Version control, CI/CD and infrastructure automation.</p><p><strong>Design for Operations</strong><br/>Health checks, logs, monitoring and diagnostic visibility.</p></div></div></div></section><section className="section section-soft"><div className="container founder-grid"><div className="founder-panel"><small>ENGINEERING LEADERSHIP</small><h2>{site.founder}</h2><p>{site.founderTitle}</p></div><div><h2>{site.professionalTitle}</h2><p>Samuel&apos;s technical background spans systems administration, cloud engineering, cloud architecture, software development, DevOps and AI/ML operations.</p><p>His engineering work includes Python, Java, JavaScript, APIs, payment systems, Microsoft Azure, AWS, Docker, Kubernetes, CI/CD and modern AI systems including OpenAI, ChatGPT, Codex, Claude and Gemini.</p><p><strong>Master of Science in Artificial Intelligence</strong><br/>The Open University of Kenya<br/>Sep 2026 - Dec 2027</p><div className="career-flow">{["Systems Administration","Cloud Engineering","Cloud Architecture","Software Engineering","DevOps","AI/ML Ops"].map(x=><span key={x}>{x}</span>)}</div><div className="links"><a className="button button-outline" href={site.linkedin}>LinkedIn</a><a className="button button-outline" href={site.github}>GitHub</a></div></div></div></section></main>;
}
